Kinematic Identification of Young Nearby Moving Groups from a Sample of Chromospherically Active Stars in the RAVE Catalog
* Ramírez-Preciado+2018:https://ui.adsabs.harvard.edu/abs/2018ApJ...867...93R/abstract

https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J/ApJ/867/93

In [2]:
import chronos as cr

key = cr.cluster.CATALOG_DICT["RamirezPreciado2018"]
tabs = cr.get_vizier_tables(key, row_limit=-1)
tabs

Downloading all tables in J/ApJ/867/93 from vizier.
{'J/ApJ/867/93/table1': 'Main parameters for the members of young nearby moving groups (YNMGs) detected with the Cone Method Sampling (CMS)', 'J/ApJ/867/93/table2': 'Main parameters for the candidates detected with the CMS'}

TableList with 2 tables:
	'0:J/ApJ/867/93/table1' with 17 column(s) and 56 row(s)
	'1:J/ApJ/867/93/table2' with 16 column(s) and 278 row(s)

In [3]:
df = cr.get_vizier_tables(key, row_limit=-1, tab_index=1)
df

Downloading all tables in J/ApJ/867/93 from vizier.

,_2MASS,RAJ2000,DEJ2000,Vmag,Jmag,pmRA,pmDE,RVel,Teff,Lbol,Mass,Age,RAVE,APASS,Gaia,Simbad
0,23123243-0240516,23 12 32.46,-02 40 51.9,12.915,10.800,17.440001,-4.568,11.995,4000.0,0.210,0.732,13.050000,RAVE,APASS,Gaia,Simbad
1,21323568-5558015,21 32 35.70,-55 58 01.6,12.473,10.987,-18.230000,-12.874,69.720,5750.0,1.924,1.238,14.730000,RAVE,APASS,Gaia,Simbad
2,23581157-3850073,23 58 11.58,-38 50 07.5,11.689,10.104,-28.778999,-30.763,4.097,4964.0,0.432,0.879,29.250000,RAVE,APASS,Gaia,Simbad
3,00220533-4050257,00 22 05.34,-40 50 25.7,13.190,11.444,-5.680000,-19.514,4.565,5000.0,0.727,1.072,15.120000,RAVE,APASS,Gaia,Simbad
4,02523097-5447531,02 52 30.99,-54 47 53.3,13.295,11.190,0.693000,-30.811,-0.920,4500.0,0.191,0.717,52.919998,RAVE,APASS,Gaia,Simbad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,21103784-5343313,21 10 37.86,-53 43 31.4,12.586,10.840,7.067000,-22.836,9.635,4508.0,0.928,1.032,3.338000,RAVE,APASS,Gaia,Simbad
274,01171093-6528593,01 17 10.93,-65 28 59.4,12.836,10.626,-11.731000,-5.741,1.742,4468.0,0.160,0.684,72.879997,RAVE,APASS,Gaia,Simbad
275,22445873-0958324,22 44 58.74,-09 58 32.4,13.474,10.743,29.447001,-9.043,12.674,3968.0,0.136,0.704,38.599998,RAVE,APASS,Gaia,Simbad
276,01023153-1745268,01 02 31.53,-17 45 26.9,12.884,10.932,39.807999,-56.852,13.380,4661.0,0.266,0.789,35.290001,RAVE,APASS,Gaia,Simbad
277,22551649-1757088,22 55 16.49,-17 57 08.9,15.365,11.952,26.737000,-5.026,28.603,3200.0,0.035,0.381,31.730000,RAVE,APASS,Gaia,Simbad

In [5]:
df['2Mname'] = df['_2MASS'].apply(lambda x: '2MASS '+x)
df['2Mname']

0      2MASS 23123243-0240516
1      2MASS 21323568-5558015
2      2MASS 23581157-3850073
3      2MASS 00220533-4050257
4      2MASS 02523097-5447531
                ...
273    2MASS 21103784-5343313
274    2MASS 01171093-6528593
275    2MASS 22445873-0958324
276    2MASS 01023153-1745268
277    2MASS 22551649-1757088
Name: 2Mname, Length: 278, dtype: object

mkdir ../../tql/tests/RamirezPreciado2018

In [7]:
df['2Mname'].to_csv("../../tql/tests/RamirezPreciado2018/ramirezPreciado2018.txt",
                  header=False,
                index=False
         )